name: Build with Ubuntu

on:
  push:
    branches:
      - build
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Install clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
        
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: "Oracle"
          java-version: "21"

      - name: Install wget
        uses: wei/wget@v1
        with:
          version: latest

      - name: Run build-CommonJS.js
        run: node ./build-CommonJS.js

      - name: Update releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release
          name: Latest_build
          files: BareIron-Ubuntu
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
