name: Build with Ubuntu

on:
  push:
    branches:
      - build
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v5

      - name: Install clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
        
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Java
        run: |
          curl -LO https://download.java.net/java/GA/jdk24.0.2/fdc5d0102fe0414db21410ad5834341f/12/GPL/openjdk-24.0.2_linux-x64_bin.tar.gz
          tar -xzf openjdk-24.0.2_linux-x64_bin.tar.gz

      - name: Install wget
        uses: wei/wget@v1

      - name: Run build-CommonJS.js
        run: node ./build-CommonJS.js

      - name: Update releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release
          name: Latest_build
          files: BareIron-Ubuntu
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
